print("Are you ready to laugh?!?!")
print("We have some amazing jokes cooking up!")
print("After each joke, rate it 1-5, 5 is best and 1 is not good!")
input("IT'S TIME!!!")
input("Knock Knock!")
input("Who's there?")
input("Broken pencil!")
input("Broken pencil who?")
print("Forget it, there's no point!!!")
rate = input("What is your rating of this joke? Type your rating here!")
print(f"Thank you for your {rate} rating!")
print("It is time for joke number 2!")
answer = input("Do you want to continue? Type 'YES' to continue and 'NO' to stop.")
if answer == 'NO':
    print("Thank you for playing! Bye!")
elif answer == 'YES':
    print("Let's continue!")
    input("Why is 6 afraid of 7?")
    print("Because 7 ate 9!!!")
    print("THANK YOU, THANK YOU!!!")